import { docsUiConfig } from '$lib/config/docs-ui';

export type DocSection = {
	title: string;
	slug: string;
	heading?: string;
	anchor?: string;
	matchType: 'title' | 'heading' | 'content';
	score: number;
	level?: number;
	content?: string;
	snippet?: string;
};

type SearchIndexEntry = {
	title: string;
	slug: string;
	heading?: string;
	anchor?: string;
	type: 'title' | 'heading' | 'content';
	level?: number;
	content?: string;
};

// Load pre-built search index (generated by build script)
let searchIndex: SearchIndexEntry[] = [];
try {
	// @ts-expect-error — generated at build time, may not exist during type-check
	const mod = await import('$lib/search-index.json');
	searchIndex = mod.default ?? mod;
} catch {
	// Search index not yet generated — search will return no results
	searchIndex = [];
}

function getSnippet(content: string, query: string, maxLength = 100): string {
	const lowerContent = content.toLowerCase();
	const lowerQuery = query.toLowerCase();
	const index = lowerContent.indexOf(lowerQuery);

	if (index === -1) return content.slice(0, maxLength);

	const start = Math.max(0, index - maxLength / 2);
	const end = Math.min(content.length, index + query.length + maxLength / 2);

	let snippet = content.slice(start, end);
	if (start > 0) snippet = '...' + snippet;
	if (end < content.length) snippet = snippet + '...';

	return snippet;
}

const pageLookup = new Map<string, string>();
searchIndex.forEach((item) => {
	if (item.type === 'title') {
		pageLookup.set(item.slug, item.title);
	}
});

export function searchDocs(query: string): DocSection[] {
	if (!query) return [];

	const normalizedQuery = query.toLowerCase();

	const groups = new Map<
		string,
		{ parent: DocSection; children: DocSection[]; maxScore: number }
	>();

	for (const item of searchIndex) {
		let score = 0;
		let snippet: string | undefined;

		const titleMatch = item.title.toLowerCase().includes(normalizedQuery);
		const headingMatch = item.heading?.toLowerCase().includes(normalizedQuery);
		const contentMatch = item.content?.toLowerCase().includes(normalizedQuery);

		if (item.type === 'title' && titleMatch) {
			score += 10;
			if (item.title.toLowerCase().startsWith(normalizedQuery)) score += 5;
		} else if (item.type === 'heading' && headingMatch) {
			score += 5;
		} else if (item.type === 'content' && contentMatch) {
			score += 1;
			if (item.content) {
				snippet = getSnippet(item.content, query);
			}
		}

		if (score > 0) {
			if (!groups.has(item.slug)) {
				groups.set(item.slug, {
					parent: {
						title: pageLookup.get(item.slug) || item.title,
						slug: item.slug,
						matchType: 'title',
						score: 0
					},
					children: [],
					maxScore: 0
				});
			}

			const group = groups.get(item.slug)!;

			if (item.type === 'title') {
				group.parent = { ...item, matchType: item.type, score };
			} else {
				group.children.push({ ...item, matchType: item.type, score, snippet });
			}

			if (score > group.maxScore) {
				group.maxScore = score;
			}
		}
	}

	const sortedGroups = Array.from(groups.values())
		.sort((a, b) => {
			const scoreDiff = b.maxScore - a.maxScore;
			if (scoreDiff !== 0) return scoreDiff;
			return a.parent.title.localeCompare(b.parent.title);
		})
		.slice(0, docsUiConfig.search.maxGroups);

	const flatResults: DocSection[] = [];

	for (const group of sortedGroups) {
		flatResults.push(group.parent);
		group.children.sort((a, b) => b.score - a.score);
		flatResults.push(...group.children.slice(0, docsUiConfig.search.maxChildrenPerGroup));
	}

	return flatResults;
}
